sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tn819/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tn819/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-646375388074"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
